baseURL = "http://www.example.com"
title = "Pupin Mathéo"
theme = "mattheme"
languageCode = "fr"
defaultContentLanguage = "fr"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Pupin Mathéo "
description = "Portfolio Pupin Mathéo "
keywords = "blog,developer,personal"
info = ["Etudiant"]
avatarURL = "images/avatar.jpg"


rtl = false
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 2
url = "https://github.com/mpupin"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://fr.linkedin.com/in/matheo-pupin"

[[params.social]]
name = "CV"
icon = "fa fa-2x fa-file-text" 
weight = 1
url = "https://mega.nz/file/0CdCHIRD#EVWZrdL8p84jRP-PlfOy3FjKlL6sgMD17R4woklYwOQ"

[languages.fr]
languageName = ":fr:"

[[languages.fr.menu.main]]
name = "A propos"
weight = 4
url = "about/"

[[languages.fr.menu.main]]
name = "Projets"
weight = 3
url = "projets/"

[[languages.fr.menu.main]]
name = "Qualifications"
weight = 1
url = "qualifications/"

[[languages.fr.menu.main]]
name = "Me contacter"
weight = 5
url = "contact/"

[[languages.fr.menu.main]]
name = "Stages"
weight = 2
url = "stages/"